# Generated by Django 3.2.9 on 2021-11-26 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletters', '0003_rename_img_newsletter_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='target',
            field=models.IntegerField(default=10),
        ),
    ]
