# Generated by Django 3.2.9 on 2021-11-27 02:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletters', '0004_auto_20211126_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='subscribed_users',
            field=models.ManyToManyField(related_name='subscribed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
