# Generated by Django 3.2.9 on 2021-11-27 03:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletters', '0005_newsletter_subscribed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='editors',
            field=models.ManyToManyField(related_name='editors', to=settings.AUTH_USER_MODEL),
        ),
    ]
